import Footer from "@components/footer";
import Header from "@components/header";
import CProjects from "@components/projects";
import { ScrolltoTop } from "@components/shared";
import type { NextPage } from "next";
import Head from "next/head";

const Projects: NextPage = () => {
  return (
    <>
      <Head>
        <title>Neljohn Cerera Portfolio Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* SCROLL UP */}
        <ScrolltoTop />

        {/* HEADER */}
        <Header />
        <main>
          <CProjects />
        </main>

        {/* FOOTER */}
        <Footer isProjectsPage />
      </>
    </>
  );
};

export default Projects;
