import type { NextPage } from "next";
import Head from "next/head";
import {
  HeroSection,
  AboutMeSection,
  WhatIdoSection,
  SkillsSection,
  ProjectSection,
  CertificatesSection,
  ContactSection,
} from "@components/home";
import Footer from "@components/footer";
import Header from "@components/header";
import { Image, ScrolltoTop } from "@components/shared";
import { img_cube } from "@assets/images";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Neljohn Cerera Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {/* SCROLL UP */}
        <ScrolltoTop />

        {/* HEADER */}
        <Header />

        <main>
          {/* HERO */}
          <HeroSection />

          {/* ABOUT ME */}
          <AboutMeSection />

          <section className="skills-whatido-section">
            {/* back ground image */}
            <div className="skills-whatido__container">
              <Image
                src={img_cube}
                alt="Skills and What I do background image"
                classname="skills-whatido__bg-img"
              />
            </div>
            {/* WHAT I DO */}
            <WhatIdoSection />
            {/* SKILLS */}
            <SkillsSection />
          </section>

          {/* PROJECTS */}
          <ProjectSection />

          {/* CERTIFICATES */}
          <CertificatesSection />

          {/* CONTACT ME */}
          <ContactSection />
        </main>

        {/* FOOTER */}
        <Footer />
      </>
    </>
  );
};

export default Home;
